### PR TITLE
Improve logging after the switch to github.com/go-kit/kit/log

### PR DESCRIPTION
**Pull request by pelov**
# Description

After the switch to github.com/go-kit/kit/log the current log output doesn't look very readable. The switch doesn't require simply using `level.Debug(logger).Log` but also formatting the logs using key value pairs.

# How Has This Been Tested?

Looked briefly at the log output in a real instance and they look better but haven't checked carefully every log line, so feel free to test it yourself and suggest improvements.

### CODE REVIEW

**Comment by pelov** [comment]
Fixes #262.

**Comment by Yannig** [comment]
Hi. Can you try to rebase your work with latest version?

**Comment by vutkin** [comment]
Hi @pelov, could you please bump version to 4.2 and do a rebase from master?

**Comment by gjrlopes** [comment]
Hi @Yannig 

This improvement was lost in the 0.5.1 version.
Due this the log have several lines without "msg" key and with "(MISSING)" as value. Check log messages below:
```
{
  "Launching connection: ": "***@192.168.1.100:1521/XE",
  "caller": "collector.go:326",
  "level": "debug",
  "ts": "2023-11-15T11:56:26.179Z"
}

{
  "caller": "collector.go:332",
  "level": "debug",
  "set max idle connections to ": 0,
  "ts": "2023-11-15T11:56:26.179Z"
}

{
  "caller": "collector.go:334",
  "level": "debug",
  "set max open connections to ": 10,
  "ts": "2023-11-15T11:56:26.179Z"
}

{
  "Successfully loaded custom metrics from: /tmp/custom-metrics.toml": "(MISSING)",
  "caller": "collector.go:389",
  "level": "info",
  "ts": "2023-11-15T11:56:27.575Z"
}

{
  "About to scrape metric: ": "(MISSING)",
  "caller": "collector.go:283",
  "level": "debug",
  "ts": "2023-11-15T11:56:27.575Z"
}

{
  "(Ignored unless Histogram type)": "(MISSING)",
  "- Metric MetricsBuckets: ": null,
  "caller": "collector.go:287",
  "level": "debug",
  "ts": "2023-11-15T11:56:27.575Z"
}
```

Example from 0.4.4:
```
{
  "caller": "main.go:364",
  "level": "debug",
  "msg": "Query result looks like",
  "ts": "2023-11-15T12:15:14.325Z",
  "value": 2090
}
```

Same message from 0.5.1:
```
{
  "Query result looks like: ": 17170432,
  "caller": "collector.go:426",
  "level": "debug",
  "ts": "2023-11-15T11:56:28.417Z"
}
```
Is it possible to reimplement it and release a new version?
Best regards

**Pull request merged**
