### PR TITLE
Fix 0.4.0 compilation problem

### PR DESCRIPTION
**Pull request by pelov**
# Description

This is a quick fix for #275 mostly by looking at how other projects use the prometheus/exporter-toolkit to parse the kingping flags.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested that the `--web.listen-address` flag is working but haven't tested the `--web.config`.

### CODE REVIEW

**Comment by vutkin** [comment]
Hi @pelov, thanks for contribution, but you need adjust README.md as well in this PR.

**Comment by pelov** [comment]
> Hi @pelov, thanks for contribution, but you need adjust README.md as well in this PR.

What needs to be fixed in the README.md file? Nothing has changed in the command line options.

**Comment by vutkin** [comment]
What I see:
- now LISTEN_ADDRESS could not be configured via env var;
- --web.config don't needed anymore (here I am not sure)?

**Comment by pelov** [comment]
The options that you see deleted in the diff (`--web.listen-address` and `--web.config`) are now added by the call to `webflag.AddFlags`. See https://github.com/prometheus/exporter-toolkit/blob/master/web/kingpinflag/flag.go.

I looked more carefully and noticed that `--web.config` is now renamed to `--web.config.file`. In addition, there is a new option `--web.systemd-socket`.

I updated the README.md file to reflect these changes.

I also tested the  `--web.config.file` option and it seems to be working, i.e. starts listening on https instead of http.

**Comment by vutkin** [comment]
Could you please update release version as well?
https://github.com/iamseth/oracledb_exporter/blob/master/Makefile#L6
Please set it to `0.4.1`

**Comment by vutkin** [comment]
Thanks, let's wait for github-action run.

**Comment by Yannig** [comment]
Hi people !

That look awesome and thanks for the contribution.

**Comment by vutkin** [comment]
@Yannig could you please rerun next pipeline https://github.com/iamseth/oracledb_exporter/actions/runs/4069569816?

**Comment by vutkin** [comment]
Hi @pelov, could you please do a rebase fork from master and do a rebase for this PR?
It should be checked with pipeline but current version using old broken one.

TIA.

**Comment by vutkin** [comment]
Good evening @Yannig , could you please approve a `pipeline run` https://github.com/iamseth/oracledb_exporter/actions/runs/4087340850?

**Comment by vutkin** [comment]
Hi @pelov, could you please do a rebase again? Sorry for this. But pipeline was broken.

**Comment by vutkin** [comment]
Hey @Yannig , could you please approve a github run https://github.com/iamseth/oracledb_exporter/actions/runs/4098822304?

**Pull request merged**
